### PR TITLE
update(infra): application dockerization

### LINKED ISSUE #35: update(infra): application dockerization
Carry out a safe and suitable configuration for the application.

1. Separation of Responsibilities
2. Resource Isolation

### PR DESCRIPTION
**Pull request by ffx64**
Here we perform a complete dockerization of the application using docker-compose.

In this dockerization we use resources to connect containers in a network for secure communication.

image

### CODE REVIEW

**Review by george-prado — APPROVED** [review]
All clear and ready for future escalation on cloud services, LGTM.

**Comment by davidfontesfelix** [comment]
LGMT

**Review by hax1zi — APPROVED** [review]
LGMT

**Review by rafael-dev2021 — COMMENTED** [review]
On my local computer, I can't create the atri-blog-backend-api image. Do I need to install something else on my computer?
I used the Ubuntu-20.04 terminals, Git Bash, CMD and PowerShell, all of which returned the same error, pull access denied for atri-blog-backend-api, repository does not exist or may require.

docker

**Comment by ffx64** [comment]
@rafael-dev2021 

Good afternoon my friend, apparently you didn't compile the project. You need to compile the project with Maven to be able to run Docker.

Follow the steps below:

1. You can use the `./mvnw Install -DskipTests` command to compile the project.
2. Build the docker container with the `docker-compose build` command
3. Now just start docker normally `docker-compose up`

**Review by rafael-dev2021 — APPROVED** [review]
LGTM

**Pull request merged**
